jobs:
  build:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: echo $(pwd)
      - run: echo $(ls)
      - run: echo $(node -v)
      - run: echo $(java --version)
      - run: echo $(javac --version)
      - run: echo $(jar --version)
      - run: echo $(jar --version)
      - run: echo $(python --version)
      - run: echo $(python3 --version)
      - run: echo $(df -h)
