name: Publish AAR to Cloudsmith

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main           # or whichever branch you want to publish from

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python (for cloudsmith-cli)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli

      - name: Push AAR + POM to Cloudsmith
        run: |
          # cloudsmith list packages ${{ secrets.CLOUDSMITH_OWNER }}/${{ secrets.CLOUDSMITH_REPO }} --api-key ${{ secrets.CLOUDSMITH_API_KEY }}
          cloudsmith push maven ${{ secrets.CLOUDSMITH_OWNER }}/${{ secrets.CLOUDSMITH_REPO }} \
            react-native-webrtc-124.0.4-cometchat-21112528.aar \
            --pom-file react-native-webrtc-124.0.4-cometchat-21112528.pom \
            --api-key ${{ secrets.CLOUDSMITH_API_KEY }}
