name: Check Java and Node Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Show versions
        run: |
          java -version
          node -v

      - name: Clone Jitsi Meet repository
        run: |
          git clone https://github.com/jitsi/jitsi-meet.git
          cd jitsi-meet
          git checkout jitsi-meet_10431
          npm i
          ./android/scripts/release-sdk.sh /tmp/repo
          ls -la
