name: Check Java and Node Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Show versions
        run: |
          java -version
          node -v

      - name: Clone Jitsi Meet repository
        run: |
          git clone https://github.com/jitsi/jitsi-meet.git
          cd jitsi-meet
          git checkout jitsi-meet_10431
          git apply ../*.patch
          npm i

      - name: Build Jitsi Meet SDK
        working-directory: jitsi-meet
        run: |
          mkdir -p ${{ runner.temp }}/repo
          ./android/scripts/release-sdk.sh ${{ runner.temp }}/repo
          ls -la ${{ runner.temp }}/repo

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jitsi-meet-sdk-artifacts
          path: ${{ runner.temp }}/repo
          retention-days: 30
