name: Create artifacts for cloudsmith

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo $(pwd)
          echo $(ls)
          echo $(node -v)
          echo $(java --version)
          echo $(javac --version)
          echo $(jar --version)
          echo $(python --version)
          echo $(python3 --version)
          echo $(df -h)
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
          echo $(df -h)

      - run: python build-webrtc.py --setup --android $(pwd)
      - run: echo $(ls)

      - run: git checkout -b build-M106 refs/remotes/branch-heads/5249
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: echo $(ls)
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: python build-webrtc.py --sync --android $(pwd)

      - run: mv test/android/org test/android/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv modules/audio_device/android/java/src/org modules/audio_device/android/java/src/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv rtc_base/java/src/org rtc_base/java/src/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv sdk/android/tests/src/org sdk/android/tests/src/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv sdk/android/instrumentationtests/src/org sdk/android/instrumentationtests/src/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv sdk/android/native_unittests/org sdk/android/native_unittests/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv sdk/android/src/java/org sdk/android/src/java/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: mv sdk/android/api/org sdk/android/api/cometchat
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*java' -exec sed -i 's/package org\.webrtc\./package cometchat\.webrtc\./g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*java' -exec sed -i 's/import org\.webrtc\./import cometchat\.webrtc\./g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*java' -exec sed -i 's/package org\.webrtc;/package cometchat\.webrtc;/g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*java' -exec sed -i 's/import static org\.webrtc\./import static cometchat\.webrtc\./g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*java' -exec sed -i 's/org\.webrtc/cometchat\.webrtc/g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*' -exec sed -i 's/org\.webrtc/cometchat\.webrtc/g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*' -exec sed -i 's|org/webrtc|cometchat/webrtc|g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*' -exec sed -i 's|org_webrtc|cometchat_webrtc|g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: find . -type f -name '*' -exec sed -i 's|jingle_peerconnection|comet_jingle_peerconnection|g' {} +
        working-directory: ./build_webrtc/webrtc/android/src/

      - run: python build-webrtc.py --build --android $(pwd)

      - name: Export Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-webrtc.zip
          path: build_webrtc/build/android/android-webrtc.zip
